# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dryerV1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(880, 723)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(13, 595, 841, 121))
        self.widget.setObjectName("widget")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.Button_connect = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_connect.sizePolicy().hasHeightForWidth())
        self.Button_connect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.Button_connect.setFont(font)
        self.Button_connect.setObjectName("Button_connect")
        self.gridLayout_17.addWidget(self.Button_connect, 0, 0, 1, 2)
        self.Button_update = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_update.sizePolicy().hasHeightForWidth())
        self.Button_update.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.Button_update.setFont(font)
        self.Button_update.setObjectName("Button_update")
        self.gridLayout_17.addWidget(self.Button_update, 0, 2, 1, 2)
        self.Button_stop = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_stop.sizePolicy().hasHeightForWidth())
        self.Button_stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.Button_stop.setFont(font)
        self.Button_stop.setObjectName("Button_stop")
        self.gridLayout_17.addWidget(self.Button_stop, 0, 4, 1, 1)
        self.comboBox_COM = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_COM.sizePolicy().hasHeightForWidth())
        self.comboBox_COM.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.comboBox_COM.setFont(font)
        self.comboBox_COM.setObjectName("comboBox_COM")
        self.comboBox_COM.addItem("")
        self.gridLayout_17.addWidget(self.comboBox_COM, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_17.addWidget(self.label_4, 1, 1, 1, 2)
        self.label_connectStatus = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_connectStatus.sizePolicy().hasHeightForWidth())
        self.label_connectStatus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_connectStatus.setFont(font)
        self.label_connectStatus.setObjectName("label_connectStatus")
        self.gridLayout_17.addWidget(self.label_connectStatus, 1, 3, 1, 2)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(10, 1, 840, 586))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_3 = QtWidgets.QFrame(self.widget1)
        self.line_3.setLineWidth(4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_Channel_M1 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_M1.sizePolicy().hasHeightForWidth())
        self.label_Channel_M1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_M1.setFont(font)
        self.label_Channel_M1.setObjectName("label_Channel_M1")
        self.gridLayout_8.addWidget(self.label_Channel_M1, 0, 0, 1, 1)
        self.lineEdit_Channel_M1 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_M1.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_M1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_M1.setFont(font)
        self.lineEdit_Channel_M1.setObjectName("lineEdit_Channel_M1")
        self.gridLayout_8.addWidget(self.lineEdit_Channel_M1, 0, 1, 1, 1)
        self.horizontalSlider_Channel_M1 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_M1.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_M1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_M1.setFont(font)
        self.horizontalSlider_Channel_M1.setMaximum(1000)
        self.horizontalSlider_Channel_M1.setPageStep(10)
        self.horizontalSlider_Channel_M1.setProperty("value", 200)
        self.horizontalSlider_Channel_M1.setSliderPosition(200)
        self.horizontalSlider_Channel_M1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_M1.setObjectName("horizontalSlider_Channel_M1")
        self.gridLayout_8.addWidget(self.horizontalSlider_Channel_M1, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_Channel_M2 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_M2.sizePolicy().hasHeightForWidth())
        self.label_Channel_M2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_M2.setFont(font)
        self.label_Channel_M2.setObjectName("label_Channel_M2")
        self.gridLayout_7.addWidget(self.label_Channel_M2, 0, 0, 1, 1)
        self.lineEdit_Channel_M2 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_M2.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_M2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_M2.setFont(font)
        self.lineEdit_Channel_M2.setObjectName("lineEdit_Channel_M2")
        self.gridLayout_7.addWidget(self.lineEdit_Channel_M2, 0, 1, 1, 1)
        self.horizontalSlider_Channel_M2 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_M2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_M2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_M2.setFont(font)
        self.horizontalSlider_Channel_M2.setMaximum(1000)
        self.horizontalSlider_Channel_M2.setPageStep(10)
        self.horizontalSlider_Channel_M2.setProperty("value", 200)
        self.horizontalSlider_Channel_M2.setSliderPosition(200)
        self.horizontalSlider_Channel_M2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_M2.setObjectName("horizontalSlider_Channel_M2")
        self.gridLayout_7.addWidget(self.horizontalSlider_Channel_M2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_Channel_M3 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_M3.sizePolicy().hasHeightForWidth())
        self.label_Channel_M3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_M3.setFont(font)
        self.label_Channel_M3.setObjectName("label_Channel_M3")
        self.gridLayout_6.addWidget(self.label_Channel_M3, 0, 0, 1, 1)
        self.lineEdit_Channel_M3 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_M3.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_M3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_M3.setFont(font)
        self.lineEdit_Channel_M3.setObjectName("lineEdit_Channel_M3")
        self.gridLayout_6.addWidget(self.lineEdit_Channel_M3, 0, 1, 1, 1)
        self.horizontalSlider_Channel_M3 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_M3.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_M3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_M3.setFont(font)
        self.horizontalSlider_Channel_M3.setMaximum(1000)
        self.horizontalSlider_Channel_M3.setPageStep(10)
        self.horizontalSlider_Channel_M3.setProperty("value", 200)
        self.horizontalSlider_Channel_M3.setSliderPosition(200)
        self.horizontalSlider_Channel_M3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_M3.setObjectName("horizontalSlider_Channel_M3")
        self.gridLayout_6.addWidget(self.horizontalSlider_Channel_M3, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_Channel_M4 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_M4.sizePolicy().hasHeightForWidth())
        self.label_Channel_M4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_M4.setFont(font)
        self.label_Channel_M4.setObjectName("label_Channel_M4")
        self.gridLayout_5.addWidget(self.label_Channel_M4, 0, 0, 1, 1)
        self.lineEdit_Channel_M4 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_M4.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_M4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_M4.setFont(font)
        self.lineEdit_Channel_M4.setObjectName("lineEdit_Channel_M4")
        self.gridLayout_5.addWidget(self.lineEdit_Channel_M4, 0, 1, 1, 1)
        self.horizontalSlider_Channel_M4 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_M4.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_M4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_M4.setFont(font)
        self.horizontalSlider_Channel_M4.setMaximum(1000)
        self.horizontalSlider_Channel_M4.setPageStep(10)
        self.horizontalSlider_Channel_M4.setProperty("value", 200)
        self.horizontalSlider_Channel_M4.setSliderPosition(200)
        self.horizontalSlider_Channel_M4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_M4.setObjectName("horizontalSlider_Channel_M4")
        self.gridLayout_5.addWidget(self.horizontalSlider_Channel_M4, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_Channel_M5 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_M5.sizePolicy().hasHeightForWidth())
        self.label_Channel_M5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_M5.setFont(font)
        self.label_Channel_M5.setObjectName("label_Channel_M5")
        self.gridLayout_4.addWidget(self.label_Channel_M5, 0, 0, 1, 1)
        self.lineEdit_Channel_M5 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_M5.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_M5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_M5.setFont(font)
        self.lineEdit_Channel_M5.setObjectName("lineEdit_Channel_M5")
        self.gridLayout_4.addWidget(self.lineEdit_Channel_M5, 0, 1, 1, 1)
        self.horizontalSlider_Channel_M5 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_M5.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_M5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_M5.setFont(font)
        self.horizontalSlider_Channel_M5.setMaximum(1000)
        self.horizontalSlider_Channel_M5.setPageStep(10)
        self.horizontalSlider_Channel_M5.setProperty("value", 200)
        self.horizontalSlider_Channel_M5.setSliderPosition(200)
        self.horizontalSlider_Channel_M5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_M5.setObjectName("horizontalSlider_Channel_M5")
        self.gridLayout_4.addWidget(self.horizontalSlider_Channel_M5, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_Channel_M6 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_M6.sizePolicy().hasHeightForWidth())
        self.label_Channel_M6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_M6.setFont(font)
        self.label_Channel_M6.setObjectName("label_Channel_M6")
        self.gridLayout_3.addWidget(self.label_Channel_M6, 0, 0, 1, 1)
        self.lineEdit_Channel_M6 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_M6.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_M6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_M6.setFont(font)
        self.lineEdit_Channel_M6.setObjectName("lineEdit_Channel_M6")
        self.gridLayout_3.addWidget(self.lineEdit_Channel_M6, 0, 1, 1, 1)
        self.horizontalSlider_Channel_M6 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_M6.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_M6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_M6.setFont(font)
        self.horizontalSlider_Channel_M6.setMaximum(1000)
        self.horizontalSlider_Channel_M6.setPageStep(10)
        self.horizontalSlider_Channel_M6.setProperty("value", 200)
        self.horizontalSlider_Channel_M6.setSliderPosition(200)
        self.horizontalSlider_Channel_M6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_M6.setObjectName("horizontalSlider_Channel_M6")
        self.gridLayout_3.addWidget(self.horizontalSlider_Channel_M6, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Channel_M7 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_M7.sizePolicy().hasHeightForWidth())
        self.label_Channel_M7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_M7.setFont(font)
        self.label_Channel_M7.setObjectName("label_Channel_M7")
        self.gridLayout_2.addWidget(self.label_Channel_M7, 0, 0, 1, 1)
        self.lineEdit_Channel_M7 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_M7.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_M7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_M7.setFont(font)
        self.lineEdit_Channel_M7.setObjectName("lineEdit_Channel_M7")
        self.gridLayout_2.addWidget(self.lineEdit_Channel_M7, 0, 1, 1, 1)
        self.horizontalSlider_Channel_M7 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_M7.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_M7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_M7.setFont(font)
        self.horizontalSlider_Channel_M7.setMaximum(1000)
        self.horizontalSlider_Channel_M7.setPageStep(10)
        self.horizontalSlider_Channel_M7.setProperty("value", 200)
        self.horizontalSlider_Channel_M7.setSliderPosition(200)
        self.horizontalSlider_Channel_M7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_M7.setObjectName("horizontalSlider_Channel_M7")
        self.gridLayout_2.addWidget(self.horizontalSlider_Channel_M7, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Channel_M8 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_M8.sizePolicy().hasHeightForWidth())
        self.label_Channel_M8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_M8.setFont(font)
        self.label_Channel_M8.setObjectName("label_Channel_M8")
        self.gridLayout.addWidget(self.label_Channel_M8, 0, 0, 1, 1)
        self.lineEdit_Channel_M8 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_M8.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_M8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_M8.setFont(font)
        self.lineEdit_Channel_M8.setObjectName("lineEdit_Channel_M8")
        self.gridLayout.addWidget(self.lineEdit_Channel_M8, 0, 1, 1, 1)
        self.horizontalSlider_Channel_M8 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_M8.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_M8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_M8.setFont(font)
        self.horizontalSlider_Channel_M8.setMaximum(1000)
        self.horizontalSlider_Channel_M8.setPageStep(10)
        self.horizontalSlider_Channel_M8.setProperty("value", 200)
        self.horizontalSlider_Channel_M8.setSliderPosition(200)
        self.horizontalSlider_Channel_M8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_M8.setObjectName("horizontalSlider_Channel_M8")
        self.gridLayout.addWidget(self.horizontalSlider_Channel_M8, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(48)
        self.line.setFont(font)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.line_4 = QtWidgets.QFrame(self.widget1)
        self.line_4.setLineWidth(4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_Channel_H1 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_H1.sizePolicy().hasHeightForWidth())
        self.label_Channel_H1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_H1.setFont(font)
        self.label_Channel_H1.setObjectName("label_Channel_H1")
        self.gridLayout_16.addWidget(self.label_Channel_H1, 0, 0, 1, 1)
        self.lineEdit_Channel_H1 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_H1.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_H1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_H1.setFont(font)
        self.lineEdit_Channel_H1.setObjectName("lineEdit_Channel_H1")
        self.gridLayout_16.addWidget(self.lineEdit_Channel_H1, 0, 1, 1, 1)
        self.horizontalSlider_Channel_H1 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_H1.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_H1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_H1.setFont(font)
        self.horizontalSlider_Channel_H1.setMaximum(1000)
        self.horizontalSlider_Channel_H1.setPageStep(10)
        self.horizontalSlider_Channel_H1.setProperty("value", 200)
        self.horizontalSlider_Channel_H1.setSliderPosition(200)
        self.horizontalSlider_Channel_H1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_H1.setObjectName("horizontalSlider_Channel_H1")
        self.gridLayout_16.addWidget(self.horizontalSlider_Channel_H1, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_16)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_Channel_H2 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_H2.sizePolicy().hasHeightForWidth())
        self.label_Channel_H2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_H2.setFont(font)
        self.label_Channel_H2.setObjectName("label_Channel_H2")
        self.gridLayout_15.addWidget(self.label_Channel_H2, 0, 0, 1, 1)
        self.lineEdit_Channel_H2 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_H2.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_H2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_H2.setFont(font)
        self.lineEdit_Channel_H2.setObjectName("lineEdit_Channel_H2")
        self.gridLayout_15.addWidget(self.lineEdit_Channel_H2, 0, 1, 1, 1)
        self.horizontalSlider_Channel_H2 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_H2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_H2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_H2.setFont(font)
        self.horizontalSlider_Channel_H2.setMaximum(1000)
        self.horizontalSlider_Channel_H2.setPageStep(10)
        self.horizontalSlider_Channel_H2.setProperty("value", 200)
        self.horizontalSlider_Channel_H2.setSliderPosition(200)
        self.horizontalSlider_Channel_H2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_H2.setObjectName("horizontalSlider_Channel_H2")
        self.gridLayout_15.addWidget(self.horizontalSlider_Channel_H2, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_15)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_Channel_H3 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_H3.sizePolicy().hasHeightForWidth())
        self.label_Channel_H3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_H3.setFont(font)
        self.label_Channel_H3.setObjectName("label_Channel_H3")
        self.gridLayout_14.addWidget(self.label_Channel_H3, 0, 0, 1, 1)
        self.lineEdit_Channel_H3 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_H3.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_H3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_H3.setFont(font)
        self.lineEdit_Channel_H3.setObjectName("lineEdit_Channel_H3")
        self.gridLayout_14.addWidget(self.lineEdit_Channel_H3, 0, 1, 1, 1)
        self.horizontalSlider_Channel_H3 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_H3.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_H3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_H3.setFont(font)
        self.horizontalSlider_Channel_H3.setMaximum(1000)
        self.horizontalSlider_Channel_H3.setPageStep(10)
        self.horizontalSlider_Channel_H3.setProperty("value", 200)
        self.horizontalSlider_Channel_H3.setSliderPosition(200)
        self.horizontalSlider_Channel_H3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_H3.setObjectName("horizontalSlider_Channel_H3")
        self.gridLayout_14.addWidget(self.horizontalSlider_Channel_H3, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_14)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_Channel_H4 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_H4.sizePolicy().hasHeightForWidth())
        self.label_Channel_H4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_H4.setFont(font)
        self.label_Channel_H4.setObjectName("label_Channel_H4")
        self.gridLayout_13.addWidget(self.label_Channel_H4, 0, 0, 1, 1)
        self.lineEdit_Channel_H4 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_H4.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_H4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_H4.setFont(font)
        self.lineEdit_Channel_H4.setObjectName("lineEdit_Channel_H4")
        self.gridLayout_13.addWidget(self.lineEdit_Channel_H4, 0, 1, 1, 1)
        self.horizontalSlider_Channel_H4 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_H4.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_H4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_H4.setFont(font)
        self.horizontalSlider_Channel_H4.setMaximum(1000)
        self.horizontalSlider_Channel_H4.setPageStep(10)
        self.horizontalSlider_Channel_H4.setProperty("value", 200)
        self.horizontalSlider_Channel_H4.setSliderPosition(200)
        self.horizontalSlider_Channel_H4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_H4.setObjectName("horizontalSlider_Channel_H4")
        self.gridLayout_13.addWidget(self.horizontalSlider_Channel_H4, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_13)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_Channel_H5 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_H5.sizePolicy().hasHeightForWidth())
        self.label_Channel_H5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_H5.setFont(font)
        self.label_Channel_H5.setObjectName("label_Channel_H5")
        self.gridLayout_12.addWidget(self.label_Channel_H5, 0, 0, 1, 1)
        self.lineEdit_Channel_H5 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_H5.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_H5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_H5.setFont(font)
        self.lineEdit_Channel_H5.setObjectName("lineEdit_Channel_H5")
        self.gridLayout_12.addWidget(self.lineEdit_Channel_H5, 0, 1, 1, 1)
        self.horizontalSlider_Channel_H5 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_H5.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_H5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_H5.setFont(font)
        self.horizontalSlider_Channel_H5.setMaximum(1000)
        self.horizontalSlider_Channel_H5.setPageStep(10)
        self.horizontalSlider_Channel_H5.setProperty("value", 200)
        self.horizontalSlider_Channel_H5.setSliderPosition(200)
        self.horizontalSlider_Channel_H5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_H5.setObjectName("horizontalSlider_Channel_H5")
        self.gridLayout_12.addWidget(self.horizontalSlider_Channel_H5, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_12)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_Channel_H6 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_H6.sizePolicy().hasHeightForWidth())
        self.label_Channel_H6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_H6.setFont(font)
        self.label_Channel_H6.setObjectName("label_Channel_H6")
        self.gridLayout_11.addWidget(self.label_Channel_H6, 0, 0, 1, 1)
        self.lineEdit_Channel_H6 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_H6.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_H6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_H6.setFont(font)
        self.lineEdit_Channel_H6.setObjectName("lineEdit_Channel_H6")
        self.gridLayout_11.addWidget(self.lineEdit_Channel_H6, 0, 1, 1, 1)
        self.horizontalSlider_Channel_H6 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_H6.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_H6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_H6.setFont(font)
        self.horizontalSlider_Channel_H6.setMaximum(1000)
        self.horizontalSlider_Channel_H6.setPageStep(10)
        self.horizontalSlider_Channel_H6.setProperty("value", 200)
        self.horizontalSlider_Channel_H6.setSliderPosition(200)
        self.horizontalSlider_Channel_H6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_H6.setObjectName("horizontalSlider_Channel_H6")
        self.gridLayout_11.addWidget(self.horizontalSlider_Channel_H6, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_Channel_H7 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_H7.sizePolicy().hasHeightForWidth())
        self.label_Channel_H7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_H7.setFont(font)
        self.label_Channel_H7.setObjectName("label_Channel_H7")
        self.gridLayout_10.addWidget(self.label_Channel_H7, 0, 0, 1, 1)
        self.lineEdit_Channel_H7 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_H7.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_H7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_H7.setFont(font)
        self.lineEdit_Channel_H7.setObjectName("lineEdit_Channel_H7")
        self.gridLayout_10.addWidget(self.lineEdit_Channel_H7, 0, 1, 1, 1)
        self.horizontalSlider_Channel_H7 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_H7.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_H7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_H7.setFont(font)
        self.horizontalSlider_Channel_H7.setMaximum(1000)
        self.horizontalSlider_Channel_H7.setPageStep(10)
        self.horizontalSlider_Channel_H7.setProperty("value", 200)
        self.horizontalSlider_Channel_H7.setSliderPosition(200)
        self.horizontalSlider_Channel_H7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_H7.setObjectName("horizontalSlider_Channel_H7")
        self.gridLayout_10.addWidget(self.horizontalSlider_Channel_H7, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_Channel_H8 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_H8.sizePolicy().hasHeightForWidth())
        self.label_Channel_H8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.label_Channel_H8.setFont(font)
        self.label_Channel_H8.setObjectName("label_Channel_H8")
        self.gridLayout_9.addWidget(self.label_Channel_H8, 0, 0, 1, 1)
        self.lineEdit_Channel_H8 = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Channel_H8.sizePolicy().hasHeightForWidth())
        self.lineEdit_Channel_H8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.lineEdit_Channel_H8.setFont(font)
        self.lineEdit_Channel_H8.setObjectName("lineEdit_Channel_H8")
        self.gridLayout_9.addWidget(self.lineEdit_Channel_H8, 0, 1, 1, 1)
        self.horizontalSlider_Channel_H8 = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_Channel_H8.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_Channel_H8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(22)
        self.horizontalSlider_Channel_H8.setFont(font)
        self.horizontalSlider_Channel_H8.setMaximum(1000)
        self.horizontalSlider_Channel_H8.setPageStep(10)
        self.horizontalSlider_Channel_H8.setProperty("value", 200)
        self.horizontalSlider_Channel_H8.setSliderPosition(200)
        self.horizontalSlider_Channel_H8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Channel_H8.setObjectName("horizontalSlider_Channel_H8")
        self.gridLayout_9.addWidget(self.horizontalSlider_Channel_H8, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Button_connect.setText(_translate("Dialog", "连接/断开设备"))
        self.Button_update.setText(_translate("Dialog", "从设备更新"))
        self.Button_stop.setText(_translate("Dialog", "开始/紧急停止"))
        self.comboBox_COM.setItemText(0, _translate("Dialog", "点击“更新”"))
        self.label_4.setText(_translate("Dialog", "连接状态："))
        self.label_connectStatus.setText(_translate("Dialog", "未连接"))
        self.label_2.setText(_translate("Dialog", "风机转速"))
        self.label_Channel_M1.setText(_translate("Dialog", "风机1："))
        self.lineEdit_Channel_M1.setText(_translate("Dialog", "20%"))
        self.label_Channel_M2.setText(_translate("Dialog", "风机2："))
        self.lineEdit_Channel_M2.setText(_translate("Dialog", "20%"))
        self.label_Channel_M3.setText(_translate("Dialog", "风机3："))
        self.lineEdit_Channel_M3.setText(_translate("Dialog", "20%"))
        self.label_Channel_M4.setText(_translate("Dialog", "风机4："))
        self.lineEdit_Channel_M4.setText(_translate("Dialog", "20%"))
        self.label_Channel_M5.setText(_translate("Dialog", "风机5："))
        self.lineEdit_Channel_M5.setText(_translate("Dialog", "20%"))
        self.label_Channel_M6.setText(_translate("Dialog", "风机6："))
        self.lineEdit_Channel_M6.setText(_translate("Dialog", "20%"))
        self.label_Channel_M7.setText(_translate("Dialog", "风机7："))
        self.lineEdit_Channel_M7.setText(_translate("Dialog", "20%"))
        self.label_Channel_M8.setText(_translate("Dialog", "风机8："))
        self.lineEdit_Channel_M8.setText(_translate("Dialog", "20%"))
        self.label_3.setText(_translate("Dialog", "加热温度"))
        self.label_Channel_H1.setText(_translate("Dialog", "加热器1："))
        self.lineEdit_Channel_H1.setText(_translate("Dialog", "20%"))
        self.label_Channel_H2.setText(_translate("Dialog", "加热器2："))
        self.lineEdit_Channel_H2.setText(_translate("Dialog", "20%"))
        self.label_Channel_H3.setText(_translate("Dialog", "加热器3："))
        self.lineEdit_Channel_H3.setText(_translate("Dialog", "20%"))
        self.label_Channel_H4.setText(_translate("Dialog", "加热器4："))
        self.lineEdit_Channel_H4.setText(_translate("Dialog", "20%"))
        self.label_Channel_H5.setText(_translate("Dialog", "加热器5："))
        self.lineEdit_Channel_H5.setText(_translate("Dialog", "20%"))
        self.label_Channel_H6.setText(_translate("Dialog", "加热器6："))
        self.lineEdit_Channel_H6.setText(_translate("Dialog", "20%"))
        self.label_Channel_H7.setText(_translate("Dialog", "加热器7："))
        self.lineEdit_Channel_H7.setText(_translate("Dialog", "20%"))
        self.label_Channel_H8.setText(_translate("Dialog", "加热器8："))
        self.lineEdit_Channel_H8.setText(_translate("Dialog", "20%"))

